# Generated by Django 4.1.7 on 2023-03-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('hairColor', models.CharField(max_length=255)),
                ('eyeColor', models.CharField(max_length=255)),
            ],
        ),
    ]
